### PR TITLE
Second assignment to an attribute does overwrite

### PR DESCRIPTION
**Pull request by rodolforg**
BelongsTo cache was not updated properly after a belongsTo assignment.

### CODE REVIEW

**Comment by taq** [comment]
Let me merge all the other changes and then I take a look on this one, ok?

**Comment by taq** [comment]
I got some conflicts and think was better to move the `if` and insert the test you made, but I refered to the pull request on the commit, please take a look.

**Comment by taq** [comment]
Just curious, are you using TORM on a pet project or on a big one? :-)

**Comment by rodolforg** [comment]
Ok.

**Comment by taq** [comment]
I'm on a big one, but not everyday, so, seems it's working fine, no one is complaining! :-D

**Pull request closed without merging**
