### PR TITLE
Allow TORM\Model::where to use SQL operators

### PR DESCRIPTION
**Pull request by gabteles**
Example usage:

```php
$keys = Key::where([
    'expire_time' => ['>=', time()]
]);
```

### CODE REVIEW

**Comment by taq** [comment]
Hey, thanks for your contribution. Let me exercise the code a little more here and try to make on the same way ActiveRecord works. I'll try to do it tomorrow, ok?

**Comment by gabteles** [comment]
Ok, fine.

**Comment by taq** [comment]
Hey, take a look on this: https://github.com/taq/torm/wiki/Collections

The way I implemented was like 

```
$keys = Key::where([
    'expire_time >= ?', time()
]);
```

This way it become for flexible for complex clauses, and it is compiled as prepared statements. And, also, is just like ActiveRecord.

**Comment by taq** [comment]
Uhn ... what do you think about the way it works now? Can we close here?

**Comment by taq** [comment]
I'll close this pull request, if any suggestions can be made on the way it works now, please let me now. Thanks!

**Pull request closed without merging**
