### PR TITLE
Add Code Climate badge in README.md

### PR DESCRIPTION
**Pull request by hugoabonizio**
I'm adding the Code Climate badge to README.md.
What you think about add Travis or another CI to run the tests?

### CODE REVIEW

**Comment by taq** [comment]
Not really a good score there, uh? :-) 
I'm not sure for Code Climate. For example, this snippet:

```
Avoid unused private fields such as '$_push_later'.

    private $_push_later   = array();
```

The `$_push_later` variable is used by an inserted trait, `Persistence.php`, so, it's not really unused and is part of an important feature.

No problem with Travis or other CI.

**Comment by hugoabonizio** [comment]
That's weird, I always use Code Climate with Ruby and I find it a very useful tool, but it seems to have some problems with PHP. Is there any better alternative in PHP ecosystem?

About adding Travis, I think that only you, as the repository owner, can enable the it on Travis. But I created #18 to help on the process.

**Comment by taq** [comment]
While we can make use of some really useful things like Cyclomatic Complexity analysis, but some warnings about unused local variables on a `foreach` may be boring and lead to create more overhead than a simple variable created. For example, on row 534 it can make me use `array_values` like this just to avoid the warning:

```php
foreach (array_values($conditions) as $value) {
            array_push($values, $value);
}
```
Not sure if calling a method will be better than iterate through the hash. Anyway, seems that Code Climate with PHP and even PHP has some weird stuff. Just check how I implemented the huge hashes to keep model information, argh. So, I'm not sure if a Code Climate badge will be a good idea if the code seems ok on some parts.

**Comment by hugoabonizio** [comment]
I agree with you, a Travis badge would be more useful.

**Comment by taq** [comment]
Anyway, thanks! :-)

**Pull request closed without merging**
